blog/urls.py
from django.urls import path
from . import views

app_name='blog'   # cretae the app name and then pass in html

urlpatterns = [
    path("",views.Blog,name="blog"),
    path("<int:pk>",views.detail,name="detail")


]

protfolio_project/urls.py
from django.contrib import admin
from django.urls import path,include
from portfolio import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home,name="home"),
    path("blog/",include("blog.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class blog(models.Model):
    title=models.CharField(max_length=100)
    desc=models.TextField()
    date=models.DateField(blank=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class user(models.Model):
    name=models.CharField(max_length=100)
    memo=models.TextField()
    image=models.ImageField(upload_to='uploads',blank=True)
    date=models.DateField()

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import blog

def Blog(request):
    #data=blog.objects.all()
    #data=blog.objects.order_by("-date")[:3]   # 3 record will show with decreasing order
    data=blog.objects.order_by
    context={"data":data}
    return render(request,"blog/blog.html",context)

def detail(request,pk):
    data=get_object_or_404(blog,pk=pk)
    return render(request,"blog/detail.html",{"data":data})

portfolio/views.py
from django.shortcuts import render
from .models import user

# Create your views here.

def home(request):
    data=user.objects.all()
    context={"data":data}
    return render(request,"portfolio/home.html",context)

templates/base/base.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <div class="container">
   
    <header class="d-flex justify-content-center py-3">

  
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'home' %}" class="nav-link active" aria-current="page">Home</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link">Blog</a></li> &nbsp;&nbsp;
          <li class="nav-item"><a href="{% static 'portfolio/YogeshKumarResume .pdf' %}" class="nav-link">Resume</a></li>
          <li class="nav-item"><a href="https://www.linkedin.com/in/yogeshkumar0/" class="nav-link">LinkdIn</a></li>
          <li class="nav-item"><a href="https://github.com/yogeshahalwat" class="nav-link">GitHub</a></li>
        </ul>

    </div>
    {% block content  %}



    {% endblock content %}

  </body>
</html>

templates/blog/blog.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}      
          <div class="container px-4 py-5" id="featured-3">
              <h2 class="pb-2 border-bottom">There are {{data.count}} blog{{data.count|pluralize:'s'}}</h2>
              
              <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">

                  {% for item in data %}  
                  <div class="feature col">
                      <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                          <img src="{% static 'portfolio/python.png' %}" alt="no img found" class="rounded float-center" width="30" length="30">   
                        </div>
                        <h3 class="fs-2 text-body-emphasis">{{item.title}}</h3>
                        <p>{{item.desc|truncatechars:299}}</p>
                        <a href="{% url 'blog:detail' item.pk %}" class="icon-link">
                            More
                        </a>
                    </div>
                    
                    {% endfor %}
                </div>
          </div>

        
{% endblock content %}

templates/blog/detail.html
{% extends 'base/base.html' %}

{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
    <div class="col-md-6 p-lg-5 mx-auto my-5">
        <h1 class="display-3 fw-bold">{{data.title}}</h1>
        <h3 class="fw-normal text-muted mb-3">{{data.desc}}</h3>
    </div>
    
</div>

{% endblock content %}

templates/portfolio/home.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}

<div class="py-5 text-center container"">

    {% for item in data %}
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <p class="lead text-body-secondary">{{item.memo}}</p>
        </div>
      </div>
    <img src="{% static 'portfolio/yogesh.jpeg' %}" alt="no img found" class="rounded float-center">  
     

    
{% endfor %}
</div>



{% endblock content %}